spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
    application:
      name: spring-cloud-config-kafeng-dev
---
spring:
  profiles: test
    application:
      name: spring-cloud-config-kafeng-test